name: bench2d
environment:
  sdk: '>=1.0.0'
dependencies:
  box2d: '>=0.1.7'
  vector_math: any
  browser: any
transformers:
- $dart2js:
    commandLineOptions: [--trust-type-annotations, --trust-primitives]